version: "3.7"
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/site.conf
      - ./php.ini:/usr/local/etc/php/php.ini
    links:
      - php
  php:
    build: ./code/
    volumes:
      - ./code:/code
